name: stew ci
description: Launch stew ci on a project

inputs:
  project-name:
    description: The project name.
    required: true


runs:
  using: 'composite'

  steps:
    - name: Setup/upgrade the python tools
      shell: bash
      run: python -m pip install --upgrade pip wheel setuptools poetry==1.1.13 --user --no-warn-script-location

    - name: Run stew ci
      shell: bash
      working-directory: coveo-stew
      run: |
        python -m poetry install
        python -m poetry run stew ci ${{ inputs.project-name }} --exact-match
