name: stew ci
description: Launch stew ci on a project

inputs:
  project-name:
    description: The project name.
    required: true
  python-version:
    description: The python version
    required: true


runs:
  using: 'composite'

  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup/upgrade the python tools
      shell: bash
      run: | 
        pipx install poetry==1.1.13 
        pipx install coveo-stew==3.0.0a5

    - name: Ensure correct python version
      shell: bash
      working-directory: ${{ inputs.project-name }}
      run: poetry env use python${{ inputs.python-version }}

    - name: Run stew ci
      shell: bash
      run: stew ci ${{ inputs.project-name }} --exact-match
