name: stew ci
description: Launch stew ci on a project

inputs:
  project-name:
    description: The project name.
    required: true


runs:
  using: 'composite'

  steps:
    - name: Setup/upgrade the python tools
      shell: bash
      run: pipx install poetry==1.1.13 coveo-stew==3.0.0a5

    - name: Run stew ci
      shell: bash
      run: |
        python -m coveo_stew ci ${{ inputs.project-name }} --exact-match
