[tool.poetry]
name = "mock-pyproject"
version = "0.1.1"
description = "an internal mock for pyproject's tests"
authors = ["Jonathan piché <jpiche@coveo.com>"]


[tool.poetry.dependencies]
python = ">=3.6"
mock-pyproject-dependency = "*"
requests = "*"


[tool.poetry.dev-dependencies]
mock-pyproject-dependency = { path = "../mock-pyproject-dependency/", develop = true }
mypy = "*"


[tool.coveo.pyproject]
pydev = false


[tool.coveo.ci]
mypy = {}



[tool.coveo.pyproject.build-dependencies]
setuptools = ">=42"
wheel = "*"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
