name: coveo-example-action
on: [push]
jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: prepare system and paths
        run: |
          apt update && apt install python3 python3-dev python3-pip gcc curl -y
          echo "/home/runner/.local/bin:/home/runner/.poetry/bin" >> $GITHUB_PATH

      - name: python setup
        run: |
          python3 -m pip install --upgrade pip setuptools wheel --user
          python3 -m pip install --upgrade git+git://github.com/python/mypy.git#egg=mypy --user
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

      - name: run mypy
        run: |
          cd coveo-example-library
          poetry install
          mypy --python-executable $(poetry run python -c "import sys; print(sys.executable)") --config-file ../mypy.ini --module coveo_example_library --module tests_coveo_example_library
