name: coveo-settings

on:
  push:
    branches:
      - main
    paths:
      - 'coveo-settings/**'
      - '!**.lock'
      - '!**.md'

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'coveo-settings/**'
      - '.github/workflows/coveo-settings.yml'
      - '!**.md'

  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to pypi.org?"
        required: false
        default: 'false'


jobs:
  pyprojectci:
    name: pyproject ci
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - name: Run stew ci
        uses: coveo/stew@main
        with:
          project-name: ${{ github.workflow }}
          python-version: ${{ matrix.python-version }}
          poetry-version: "<2"

  publish:
    name: Publish to pypi.org
    runs-on: ubuntu-20.04
    needs: pyprojectci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Publish to pypi
        uses: ./.github/workflows/actions/publish-to-pypi
        with:
          project-name: ${{ github.workflow }}
          pypi-token: ${{ secrets.PYPI_TOKEN_COVEO_SETTINGS }}
          pre-release: ${{ github.ref != 'refs/heads/main' }}
          dry-run: ${{ github.ref != 'refs/heads/main' && github.event.inputs.publish != 'true' }}
