name: coveo-ref

on:
  push:
    branches:
      - main
    paths:
      - 'coveo-ref/**'
      - '!**.lock'
      - '!**.md'

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'coveo-ref/**'
      - '.github/workflows/coveo-ref.yml'
      - '!**.md'

  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to pypi.org?"
        required: false
        default: 'false'


jobs:
  stew-ci:
    name: pyproject ci
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Run stew ci
        uses: coveo/stew@main
        with:
          project-name: ${{ github.workflow }}
          python-version: ${{ matrix.python-version }}
          poetry-version: "<3"

  publish:
    name: Publish to pypi.org
    runs-on: ubuntu-latest
    needs: stew-ci

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup python 3.10
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: "3.10"

      - name: Publish to pypi
        uses: ./.github/workflows/actions/publish-to-pypi
        with:
          project-name: ${{ github.workflow }}
          pypi-token: ${{ secrets.PYPI_TOKEN_COVEO_REF }}
          pre-release: ${{ github.ref != 'refs/heads/main' }}
          dry-run: ${{ github.ref != 'refs/heads/main' && github.event.inputs.publish != 'true' }}
