name: coveo-example-library

on:
  push:
    branches:
      - main
    paths:
      - 'coveo-example-library/**'
      - '.github/workflows/**'

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'coveo-example-library/**'
      - '.github/workflows/**'

jobs:
  pyprojectci:
    name: pyproject ci
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, "3.10"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run stew ci
        uses: ./.github/workflows/actions/stew-ci
        with:
          project-name: ${{ github.workflow }}
          python-version: ${{ matrix.python-version }}

  publish:
    name: Publish to pypi.org
    runs-on: ubuntu-20.04
    needs: pyprojectci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Publish to pypi
        uses: ./.github/workflows/actions/publish-to-pypi
        with:
          project-name: ${{ github.workflow }}
          pypi-token: ${{ secrets.PYPI_TOKEN_COVEO_EXAMPLE_LIBRARY }}
          pre-release: ${{ github.ref != 'refs/heads/main' }}
          dry-run: true
