# the name of the workflow must match the name of the project and project folder.
name: coveo-example-library
on: [push]
jobs:
  check_if_changed:
    runs-on: ubuntu-20.04
    env:
      PROJECT_FOLDER: coveo-example-library

    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: check_changes
        run: |
          if git diff ${{ github.sha }} --name-only | grep '^${{ github.workflow }}/'; then
              echo "Changes detected!"
              echo "::set-output name=changes_detected::true"
          else
              echo "No changes detected!"
              echo "::set-output name=changes_detected::false"
          fi


  pyprojectci:
    runs-on: ubuntu-20.04
    needs: check_if_changed
    if: needs.check_if_changed.outputs.changes_detected == 'true'
    steps:
      - name: prepare system and paths
        run: |
          apt update && apt install python3 python3-dev python3-pip gcc curl -y
          echo "/home/runner/.local/bin:/home/runner/.poetry/bin" >> $GITHUB_PATH

      - name: python setup
        run: python3 -m pip install --upgrade setuptools wheel ./coveo-pyproject --user

      - name: run pyproject ci
        run: |
          pyproject ci ${{ github.workflow }}
