# the name of the workflow, the library name and the source folder name must be the same.
name: coveo-example-library
on: [push]

jobs:
  check-if-changed:
    name: detect changes
    runs-on: ubuntu-20.04
    if: github.ref != 'refs/heads/main'

    outputs:
      changes-detected: ${{ steps.detect-changes.outputs.changes-detected }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ${{ format('actions/detect-changes@{0}', github.sha) }}
        id: detect-changes
        with:
          folder: ${{ github.workflow }}/


  pyprojectci:
    name: pyproject ci
    runs-on: ubuntu-20.04
    needs: check-if-changed
    if: (github.ref == 'refs/heads/main') || (needs.check-if-changed.outputs.changes-detected == 'true')
    steps:
      - uses: actions/checkout@v2

      - name: prepare system and paths
        run: |
          apt update && apt install python3 python3-dev python3-pip gcc curl -y
          echo "/home/runner/.local/bin:/home/runner/.poetry/bin" >> $GITHUB_PATH

      - name: python setup
        run: |
          python3 -m pip install --upgrade setuptools wheel --user
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

      - name: install pyproject
        run: |
          cd coveo-pyproject
          poetry install

      - name: run pyproject ci
        run: |
          cd coveo-pyproject
          poetry run pyproject ci ${{ github.workflow }} --exact-match
